#!/usr/bin/env ruby
#encoding: utf-8

require 'strelka'


# A little CORS demo app
class CORSDemoApp < Strelka::App

	# App ID
	ID = 'cors-demo'

	# Load some plugins
	plugins :templating, :routing

	# By default, responses are HTML
	default_type 'text/html'

	# Templating -- wrap everything in the layout
	layout 'layout.tmpl'
	templates \
		:top => 'top.tmpl'


	# GET request handler -- handles all GET requests
	get do |req|
		# Use the 'top' template for the body, wrapped in the 'layout' template
		return :top
	end


end # class CORSDemoApp


CORSDemoApp.run if __FILE__ == $0

